language: node_js
node_js:
  - "4.0"
  - "5.0"
  - "stable"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  CXX=g++-4.8
notifications:
  email:
    on_success: change
